# ì €ì¥ì†Œì˜ Action íƒ­ì—ì„œ í‘œì‹œë  ì›Œí¬í”Œë¡œìš° ì´ë¦„
name: ğŸ‘¨â€ğŸ”¬ CI - Test

on:
  # ì›Œí¬í”Œë¡œìš°ë¥¼ ê¹ƒí—ˆë¸Œì—ì„œ ì§ì ‘ ì‹¤í–‰í•  ìˆ˜ ìˆê²Œ í•´ì£¼ëŠ” ì˜µì…˜
  workflow_dispatch:
  # S015/feat/#68 ë¸Œëœì¹˜ì—ì„œ pushë‚˜ pull request ì´ë²¤íŠ¸ ë°œìƒ ì‹œ í•´ë‹¹ workflowê°€ íŠ¸ë¦¬ê±°ë¨
  push:
    branches: [ "S015/feat/#68" ]
  pull_request:
    branches: [ "S015/feat/#68" ]

# í•˜ë‚˜ ì´ìƒì˜ Jobìœ¼ë¡œ êµ¬ì„± ê°€ëŠ¥
jobs:
  # ë¹Œë“œë¥¼ ìˆ˜í–‰í•˜ëŠ” Jobì˜ ì´ë¦„
  build:
    # ê¹ƒí—ˆë¸Œ ì•¡ì…˜ UIì—ì„œ í‘œì‹œë  Job ì´ë¦„
    name: Test
    # Jobì„ ì‹¤í–‰í•  OS í™˜ê²½
    runs-on: macos-latest

    # Jobì´ ì‹¤í–‰í•  Stepë“¤
    steps:
      # usesë¥¼ ì‚¬ìš©í•˜ë©´ ê¹ƒí—ˆë¸Œ ì•¡ì…˜ì—ì„œ ê¸°ë³¸ì ìœ¼ë¡œ ì œê³µí•˜ëŠ” Actionì„ ì‚¬ìš©í•  ìˆ˜ ìˆë‹¤.
      # ë ˆí¬ì§€í† ë¦¬ ì½”ë“œë¥¼ ì²´í¬ì•„ì›ƒí•˜ëŠ” ë™ì‘. ì´ ì‘ì—…ì„ í†µí•´ ì›Œí¬í”Œë¡œìš°ê°€ í˜„ì¬ ì½”ë“œë² ì´ìŠ¤ì— ì ‘ê·¼í•  ìˆ˜ ìˆê²Œ ëœë‹¤.
      - name: Checkout
        uses: actions/checkout@v4

      # í•´ë‹¹ ê°€ìƒ ë¨¸ì‹  í™˜ê²½ì—ì„œì˜ ê°€ìš© Xcode ë²„ì „ì„ ì¶œë ¥
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode

      # í˜„ì¬ Xcode ë²„ì „ ì¶œë ¥
      - name: Show current version of Xcode
        run: xcodebuild -version

      # SwiftLint í”ŒëŸ¬ê·¸ì¸ í™œì„±í™” í™•ì¸
      - name: Verify SwiftLint Plugin
        run: |
          if ! xcodebuild -resolvePackageDependencies -scheme Molio; then
            echo "SwiftLint plugin or dependencies could not be resolved."
            exit 1
          fi
          
      # í…ŒìŠ¤íŠ¸ ìŠ¤í¬ë¦½íŠ¸ ì‹¤í–‰
      - name: Run tests
        run: |
          ./run_tests.sh